# Generated by Django 3.0.10 on 2020-11-01 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='data-fathom - This is the slug that populates data-fathom.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of label.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='freeze_software',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Software used for freezing'),
        ),
        migrations.AddField(
            model_name='sample',
            name='page_size',
            field=models.IntegerField(blank=True, help_text="This is updated on save, don't bother manually changing.", null=True, verbose_name='Page size'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='frozen_page',
            field=models.TextField(verbose_name='Frozen page'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='Url of frozen page'),
        ),
        migrations.CreateModel(
            name='LabeledSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_sample', models.TextField(help_text='Sample page modified with labeling ids. This is mutable.')),
                ('original_sample', models.OneToOneField(help_text='Link to the original sample', on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='LabeledElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fta_id', models.SlugField(help_text='data-fta_id - This is the id in the Labeled Sample.', max_length=64)),
                ('label', models.ForeignKey(help_text='data-fta_id - This is the id in the Labeled Sample.', on_delete=django.db.models.deletion.CASCADE, to='samples.Label')),
                ('labeled_sample', models.ForeignKey(help_text='Link to labeled sample', on_delete=django.db.models.deletion.CASCADE, to='samples.LabeledSample')),
            ],
        ),
    ]
