# Generated by Django 3.0.10 on 2020-10-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='freeze_software',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Software used for freezing'),
        ),
    ]
