# Generated by Django 3.0.10 on 2020-11-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20201031_2352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labeledelement',
            unique_together={('data_fta_id', 'labeled_sample')},
        ),
    ]
