# Generated by Django 3.0.10 on 2020-10-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20201027_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='page_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page size'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='frozen_page',
            field=models.TextField(verbose_name='Freeze-dried page'),
        ),
    ]
