# Generated by Django 3.0.10 on 2020-11-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20201104_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='page_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page height in pixels'),
        ),
        migrations.AddField(
            model_name='sample',
            name='page_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page width in pixels'),
        ),
    ]
