# Generated by Django 3.0.10 on 2020-11-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20201107_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledelement',
            name='labeled_sample',
            field=models.ForeignKey(help_text='Link to labeled sample', on_delete=django.db.models.deletion.CASCADE, related_name='labeled_elements', to='samples.LabeledSample'),
        ),
    ]
