# Generated by Django 3.0.10 on 2020-10-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20201029_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.SlugField(help_text='data-fathom - This is the slug that populates data-fathom.', unique=True),
        ),
    ]
