# Generated by Django 3.0.10 on 2020-11-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20201109_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledsample',
            name='original_sample',
            field=models.OneToOneField(help_text='Link to the original sample', on_delete=django.db.models.deletion.CASCADE, related_name='labeled_sample', to='samples.Sample'),
        ),
    ]
