# Generated by Django 3.0.10 on 2021-01-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20210112_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledsample',
            name='superseded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labeled_sample', to='samples.LabeledSample'),
        ),
    ]
