# Generated by Django 3.0.10 on 2021-01-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_labeledsample_superseded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledsample',
            name='superseded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superseded_labeled_samples', to='samples.LabeledSample'),
        ),
    ]
